### ISSUE TITLE
scrpit isn't working

### ISSUE THREAD

**Issue by ersalil** [yaworsk/hackerone_scrapper#2]
cmd : sudo ruby hackerone_scrapper.rb
error : - 
hackerone_scrapper.rb:10: warning: calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open
Loaded https://hackerone.com/hacktivity
Traceback (most recent call last):
	1: from hackerone_scrapper.rb:31:in `<main>'
hackerone_scrapper.rb:18:in `load_page': undefined method `[]' for nil:NilClass (NoMethodError)

so please help to resolve the problem asap.

**Comment by yaworsk** [comment]
This is old and things have probably changed. I don't maintain this so can't help resolve the problem. I'm sure there are better resources now.
